"""L3 node test for racer_tools' raceline_publisher_node (claude-docs/12-testing.md,
roadmap milestone 3).

Same pytest.importorskip-guarded shape as
sim/bridge/racer_gym_bridge/test/test_bridge_node.py: this module is skipped cleanly under
the bare `uv run pytest` L1 run (racer_tools/pyproject.toml has no rclpy/launch_testing --
see that file's own docstring), and runs for real under `colcon test` in the ros-dev image
(the l3-and-cpp CI job), which has the full ROS install.

Checklist covered: nominal behavior (the raceline's points show up on /sim/raceline with
the right frame id and a closed loop) and QoS (transient_local latching -- a subscriber
that connects well after startup still gets the one message; a volatile one does not). The
fail-closed "missing raceline_path parameter refuses to start" check lives in
test_raceline_publisher_node_fails_closed.py instead -- it constructs the node directly
rather than through a managed launch, which does not mix well with this file's
launch_testing active-phase machinery."""

from __future__ import annotations

import signal
import tempfile
import time
import unittest

import pytest

pytest.importorskip("rclpy")
pytest.importorskip("launch_testing")

import launch
import launch_testing
import launch_testing.actions
import launch_testing.asserts
import rclpy
from launch_ros.actions import Node as LaunchNode
from nav_msgs.msg import Path
from rclpy.qos import DurabilityPolicy, HistoryPolicy, QoSProfile, ReliabilityPolicy

_FIXTURE_RACELINE_CSV = """\
# raceline for track_id=test_square (claude-docs/02-repo-layout.md)
# generated by hand for ros_ws/src/racer_tools/test/test_raceline_publisher_node_launch.py
# vehicle_params: schema_version=0.1.0, sysid_session_id=none-preliminary
# generation_params: track_shape=square
# columns: s_m,x_m,y_m,heading_rad,curvature_1pm,target_speed_mps
s_m,x_m,y_m,heading_rad,curvature_1pm,target_speed_mps
0.0,0.0,0.0,0.0,0.0,3.0
2.0,2.0,0.0,1.57,0.0,3.0
4.0,2.0,2.0,3.14,0.0,3.0
6.0,0.0,2.0,-1.57,0.0,3.0
"""


def _write_fixture_raceline() -> str:
    tmp_dir = tempfile.mkdtemp()
    path = f"{tmp_dir}/raceline.csv"
    with open(path, "w") as f:
        f.write(_FIXTURE_RACELINE_CSV)
    return path


def _transient_local_qos() -> QoSProfile:
    return QoSProfile(
        reliability=ReliabilityPolicy.RELIABLE,
        durability=DurabilityPolicy.TRANSIENT_LOCAL,
        history=HistoryPolicy.KEEP_LAST,
        depth=1,
    )


_RACELINE_PATH = _write_fixture_raceline()


@pytest.mark.launch_test
def generate_test_description():
    raceline_publisher_node = LaunchNode(
        package="racer_tools",
        executable="raceline_publisher_node",
        name="raceline_publisher_node",
        parameters=[{"raceline_path": _RACELINE_PATH}],
    )
    return launch.LaunchDescription(
        [
            raceline_publisher_node,
            launch_testing.actions.ReadyToTest(),
        ]
    )


class TestRacelinePublisherNode(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        rclpy.init()

    @classmethod
    def tearDownClass(cls):
        rclpy.shutdown()

    def setUp(self):
        self.node = rclpy.create_node("raceline_publisher_test_client")

    def tearDown(self):
        self.node.destroy_node()

    def _spin_for(self, seconds: float) -> None:
        end = time.time() + seconds
        while time.time() < end:
            rclpy.spin_once(self.node, timeout_sec=0.05)

    def test_publishes_the_raceline_as_a_closed_loop_path_in_the_map_frame(self):
        received = []
        self.node.create_subscription(
            Path, "/sim/raceline", received.append, _transient_local_qos()
        )
        self._spin_for(2.0)

        self.assertEqual(len(received), 1, "expected exactly one latched /sim/raceline message")
        msg = received[0]
        self.assertEqual(msg.header.frame_id, "map")
        # 4 raceline points + 1 repeated closing point (raceline_path_builder.py).
        self.assertEqual(len(msg.poses), 5)
        first, last = msg.poses[0], msg.poses[-1]
        self.assertAlmostEqual(first.pose.position.x, last.pose.position.x)
        self.assertAlmostEqual(first.pose.position.y, last.pose.position.y)
        self.assertAlmostEqual(msg.poses[1].pose.position.x, 2.0)
        self.assertAlmostEqual(msg.poses[1].pose.position.y, 0.0)

    def test_a_late_joining_subscriber_still_receives_the_latched_message(self):
        # No subscriber created yet -- let the node run a while, THEN subscribe, proving
        # transient_local latching actually works (same pattern as
        # sim/bridge/racer_gym_bridge/test/test_bridge_node.py's map latch test).
        self._spin_for(1.0)
        received = []
        self.node.create_subscription(
            Path, "/sim/raceline", received.append, _transient_local_qos()
        )
        self._spin_for(2.0)
        self.assertEqual(len(received), 1)

    def test_a_volatile_subscriber_does_not_receive_it(self):
        volatile_qos = QoSProfile(
            reliability=ReliabilityPolicy.RELIABLE,
            durability=DurabilityPolicy.VOLATILE,
            history=HistoryPolicy.KEEP_LAST,
            depth=1,
        )
        self._spin_for(1.0)
        received = []
        self.node.create_subscription(Path, "/sim/raceline", received.append, volatile_qos)
        self._spin_for(2.0)
        self.assertEqual(
            len(received),
            0,
            "a volatile subscriber connecting after startup must NOT see the latched message",
        )


@launch_testing.post_shutdown_test()
class TestRacelinePublisherNodeShutdown(unittest.TestCase):
    def test_exit_codes(self, proc_info):
        # Either a clean exit(0) or "terminated by SIGINT" is allowable (same reasoning as
        # sim/bridge/racer_gym_bridge/test/test_bridge_node.py's shutdown test): launch_testing
        # sends SIGINT to end the test, and rclpy's own SIGINT handler racing this node's own
        # shutdown path can land either way.
        launch_testing.asserts.assertExitCodes(proc_info, allowable_exit_codes=[0, -signal.SIGINT])
