"""L1 tests for racer_tools.raceline_loader (claude-docs/12-testing.md), pure/ROS-free.

Same fixture/edge-case shape as
sim/bridge/racer_gym_bridge/test/test_track_loader.py's tests for the same CSV format
(deliberately not shared code across colcon workspaces -- see raceline_loader.py's own
docstring)."""

from __future__ import annotations

import pytest
from racer_tools.raceline_loader import RacelineLoadError, RacelinePoint, load_raceline_points

_FIXTURE_CSV = """\
# raceline for track_id=test_track (claude-docs/02-repo-layout.md)
# generated by hand for ros_ws/src/racer_tools/test/test_raceline_loader.py
# vehicle_params: schema_version=0.1.0, sysid_session_id=none-preliminary
# generation_params: track_shape=square
# columns: s_m,x_m,y_m,heading_rad,curvature_1pm,target_speed_mps
s_m,x_m,y_m,heading_rad,curvature_1pm,target_speed_mps
0.0,0.0,0.0,0.0,0.0,3.0
1.0,1.0,0.0,1.57,0.0,4.0
2.0,1.0,1.0,3.14,0.0,5.0
"""


def test_loads_points_in_file_order(tmp_path):
    path = tmp_path / "raceline.csv"
    path.write_text(_FIXTURE_CSV)

    points = load_raceline_points(path)

    assert points == [
        RacelinePoint(0.0, 0.0, 0.0, 0.0, 0.0, 3.0),
        RacelinePoint(1.0, 1.0, 0.0, 1.57, 0.0, 4.0),
        RacelinePoint(2.0, 1.0, 1.0, 3.14, 0.0, 5.0),
    ]


def test_accepts_a_path_string_not_just_a_path_object(tmp_path):
    path = tmp_path / "raceline.csv"
    path.write_text(_FIXTURE_CSV)
    points = load_raceline_points(str(path))
    assert len(points) == 3


def test_ignores_comment_and_blank_lines(tmp_path):
    path = tmp_path / "raceline.csv"
    path.write_text(
        "# a comment\n\ns_m,x_m,y_m,heading_rad,curvature_1pm,target_speed_mps\n"
        "\n0.0,0.0,0.0,0.0,0.0,3.0\n# trailing comment\n"
    )
    points = load_raceline_points(path)
    assert points == [RacelinePoint(0.0, 0.0, 0.0, 0.0, 0.0, 3.0)]


def test_raises_on_missing_file(tmp_path):
    with pytest.raises(RacelineLoadError):
        load_raceline_points(tmp_path / "does_not_exist.csv")


def test_raises_on_bad_header(tmp_path):
    path = tmp_path / "raceline.csv"
    path.write_text("not,the,right,header\n1,2,3,4\n")
    with pytest.raises(RacelineLoadError):
        load_raceline_points(path)


def test_raises_on_no_header_row_at_all(tmp_path):
    path = tmp_path / "raceline.csv"
    path.write_text("# only comments\n# no header, no data\n")
    with pytest.raises(RacelineLoadError):
        load_raceline_points(path)


def test_raises_on_empty_body(tmp_path):
    path = tmp_path / "raceline.csv"
    path.write_text("s_m,x_m,y_m,heading_rad,curvature_1pm,target_speed_mps\n")
    with pytest.raises(RacelineLoadError):
        load_raceline_points(path)


def test_raises_on_non_numeric_field(tmp_path):
    path = tmp_path / "raceline.csv"
    path.write_text(
        "s_m,x_m,y_m,heading_rad,curvature_1pm,target_speed_mps\n0.0,not_a_number,0.0,0.0,0.0,3.0\n"
    )
    with pytest.raises(RacelineLoadError):
        load_raceline_points(path)


def test_raises_on_wrong_field_count(tmp_path):
    path = tmp_path / "raceline.csv"
    path.write_text("s_m,x_m,y_m,heading_rad,curvature_1pm,target_speed_mps\n0.0,0.0,0.0,0.0,0.0\n")
    with pytest.raises(RacelineLoadError):
        load_raceline_points(path)
