// firmware/safety_mux Pico SDK glue: main loop tying the host-tested decision logic in
// firmware/safety_mux/logic/ to real RP2040 GPIO/PWM hardware. UNVERIFIED ON HARDWARE -- see
// firmware/safety_mux/README.md for what that means and what roadmap task 1.3's kill test
// still has to prove. This file is deliberately thin: every actual DECISION (mux state
// machine, watchdog timing, PWM validity) lives in logic/ and is called, never
// re-implemented, here.
//
// Pin assignments below match firmware/safety_mux/README.md's pinout table exactly --
// change one, change both, or the README stops being honest about what this code does.
#include <stdio.h>

#include "hardware/gpio.h"
#include "pico/stdlib.h"
#include "safety_mux/mux_decision.h"
#include "safety_mux/mux_params.h"
#include "safety_mux/rc_switch.h"
#include "vehicle_params_generated.h"  // generated by tools/gen_params.py at build time, see
                                        // CMakeLists.txt -- never hand-written, never committed
                                        // (claude-docs/06-vehicle-params.md rule 3)

#include "heartbeat_input.h"
#include "power_cutoff.h"
#include "pwm_capture.h"
#include "pwm_output.h"

#define RC_KILL_SWITCH_GPIO 2
#define JETSON_STEERING_PWM_IN_GPIO 3
#define JETSON_THROTTLE_PWM_IN_GPIO 4
#define JETSON_HEARTBEAT_GPIO 5
#define SERVO_PWM_OUT_GPIO 6
#define ESC_PWM_OUT_GPIO 7
#define POWER_CUTOFF_GPIO 8
#define FAULT_LED_GPIO PICO_DEFAULT_LED_PIN

#define MUX_LOOP_PERIOD_MS 5  // 200 Hz -- comfortably faster than a 50 Hz servo/ESC frame

// Builds a RawMuxParamFields from the generated vehicle_params C binding
// (vehicle_params_generated.h's static const VEHICLE_PARAMS instance, tools/gen_params.py's
// C emitter -- every nullable leaf there is a `<field>` + `<field>_is_set` pair). This is
// the ONE place safety_mux/mux_params.h's field names are wired to vehicle_params' actual
// schema paths; if config/vehicle_params.schema.json's field names ever change, this is
// where the build breaks (a compile error, not a silent mismatch).
static RawMuxParamFields raw_fields_from_generated_params(void) {
  RawMuxParamFields raw;
  raw.steering_pwm_min_us.value = VEHICLE_PARAMS.steering.pwm_min_us;
  raw.steering_pwm_min_us.is_set = VEHICLE_PARAMS.steering.pwm_min_us_is_set;
  raw.steering_pwm_max_us.value = VEHICLE_PARAMS.steering.pwm_max_us;
  raw.steering_pwm_max_us.is_set = VEHICLE_PARAMS.steering.pwm_max_us_is_set;
  raw.steering_pwm_neutral_us.value = VEHICLE_PARAMS.steering.pwm_neutral_us;
  raw.steering_pwm_neutral_us.is_set = VEHICLE_PARAMS.steering.pwm_neutral_us_is_set;
  raw.throttle_pwm_min_us.value = VEHICLE_PARAMS.actuation.throttle_pwm_min_us;
  raw.throttle_pwm_min_us.is_set = VEHICLE_PARAMS.actuation.throttle_pwm_min_us_is_set;
  raw.throttle_pwm_max_us.value = VEHICLE_PARAMS.actuation.throttle_pwm_max_us;
  raw.throttle_pwm_max_us.is_set = VEHICLE_PARAMS.actuation.throttle_pwm_max_us_is_set;
  raw.throttle_pwm_neutral_us.value = VEHICLE_PARAMS.actuation.throttle_pwm_neutral_us;
  raw.throttle_pwm_neutral_us.is_set = VEHICLE_PARAMS.actuation.throttle_pwm_neutral_us_is_set;
  raw.watchdog_timeout_s.value = VEHICLE_PARAMS.limits.mux_watchdog_timeout_s;
  raw.watchdog_timeout_s.is_set = VEHICLE_PARAMS.limits.mux_watchdog_timeout_s_is_set;
  raw.kill_switch_threshold_us.value = VEHICLE_PARAMS.limits.mux_kill_switch_threshold_us;
  raw.kill_switch_threshold_us.is_set =
      VEHICLE_PARAMS.limits.mux_kill_switch_threshold_us_is_set;
  // The kill switch's ARM/KILL dead band is not a vehicle_params field yet -- see
  // logic/include/safety_mux/rc_switch.h's RC_SWITCH_DEFAULT_HYSTERESIS_US for why, and
  // docs/notes/firmware-review-2026-09-14.md for the follow-up that makes it one. Supplied
  // here, like the RC signal range below, rather than left unset, so a genuinely missing
  // vehicle_params field is the only thing the fault path can ever be about.
  raw.kill_switch_hysteresis_us.value = RC_SWITCH_DEFAULT_HYSTERESIS_US;
  raw.kill_switch_hysteresis_us.is_set = true;
  // The RC receiver's own valid PWM signal range is NOT a vehicle_params field (it describes
  // the receiver/transmitter pair, not the vehicle) -- see README.md's pinout table. Bench
  // work must replace this with the receiver's datasheet-or-measured range before this
  // firmware leaves draft status; it is set here (not left to default-construct as unset)
  // specifically so that omission does not read as "just another missing vehicle_params
  // field" in the fault path below.
  raw.rc_signal_min_us.value = 1000.0;
  raw.rc_signal_min_us.is_set = true;
  raw.rc_signal_max_us.value = 2000.0;
  raw.rc_signal_max_us.is_set = true;
  return raw;
}

static const char* problem_text(MuxParamProblem problem) {
  switch (problem) {
    case MUX_PARAM_PROBLEM_MISSING:
      return "is null (unmeasured)";
    case MUX_PARAM_PROBLEM_NOT_FINITE:
      return "is NaN or infinite";
    case MUX_PARAM_PROBLEM_RANGE:
      return "is out of range or inconsistent with the other fields";
    case MUX_PARAM_PROBLEM_NONE:
      break;
  }
  return "is unusable";
}

// Halts forever, blinking the fault LED and printing over USB serial, rather than running
// the control loop with an assumed default (CLAUDE.md invariant 2; this milestone's
// instruction: "the firmware build must fail loudly on nulls rather than assume defaults").
// Deliberately never returns.
//
// SAFE-STATE PRECONDITION: main() drives the power cutoff and both PWM output pins to their
// safe states BEFORE it reads any param, so reaching here leaves GPIO 6/7 driven LOW (no
// pulses, nothing for a servo or an ESC to act on) and GPIO 8 LOW (power cut) for as long as
// the board stays powered. This function must never be called before that has happened.
static void fault_halt_missing_param(const char* field, MuxParamProblem problem) {
  gpio_init(FAULT_LED_GPIO);
  gpio_set_dir(FAULT_LED_GPIO, GPIO_OUT);
  while (true) {
    printf("FATAL: safety_mux param '%s' %s.\n", field, problem_text(problem));
    printf("This firmware refuses to arm without every field it needs. Outputs are held "
           "inert (no PWM pulses, power cutoff open). See "
           "firmware/safety_mux/README.md.\n");
    gpio_put(FAULT_LED_GPIO, true);
    sleep_ms(100);
    gpio_put(FAULT_LED_GPIO, false);
    sleep_ms(100);
  }
}

int main(void) {
  // --- Step 1, before anything else: every output pin to its safe state. ----------------
  // Nothing above this line may touch hardware. The RP2040 comes out of reset with its GPIOs
  // as high-impedance inputs, so until these three calls run, the servo signal line, the ESC
  // signal line, and the power-cutoff drive line are all FLOATING. A floating servo input can
  // twitch the servo; a floating ESC input is the condition some ESCs arm on; a floating
  // cutoff line is undefined at exactly the moment the cutoff is supposed to be open. None of
  // this depends on config/vehicle_params.yaml being readable, so none of it waits for that.
  //
  // Driven LOW is "no pulses", NOT the mux's neutral: the configured neutral cannot be known
  // until the params are validated a few lines down, and inventing one would be the silent
  // default CLAUDE.md invariant 2 exists to prevent. Low is the correct state for that gap,
  // and it is also the state the pins keep forever if the firmware refuses to arm.
  power_cutoff_init(POWER_CUTOFF_GPIO);  // GPIO 8 LOW = power cut
  pwm_output_init_safe(SERVO_PWM_OUT_GPIO);
  pwm_output_init_safe(ESC_PWM_OUT_GPIO);

  stdio_init_all();

  // --- Step 2: params, or refuse. -------------------------------------------------------
  RawMuxParamFields raw = raw_fields_from_generated_params();
  MuxParamsResult params_result = mux_params_from_raw(raw);
  if (!params_result.ok) {
    fault_halt_missing_param(params_result.missing_field, params_result.problem);
    // unreachable: fault_halt_missing_param() never returns.
  }
  MuxParams params = params_result.params;

  // --- Step 3: the outputs go to the configured NEUTRAL, still before any input exists. --
  // This is the first moment a neutral is known, and it is applied immediately rather than
  // waiting for the first loop iteration, so there is no frame in which the pins are
  // configured as PWM outputs carrying something other than neutral. The cut state is now
  // fully established: neutral on both channels, cutoff open.
  pwm_output_init_channel(SERVO_PWM_OUT_GPIO, params.steering_pwm_neutral_us);
  pwm_output_init_channel(ESC_PWM_OUT_GPIO, params.throttle_pwm_neutral_us);

  // --- Step 4: only now start listening to the outside world. ---------------------------
  // Capture and heartbeat come last on purpose: every one of them starts in its "nothing
  // observed yet" state (-1.0 and +Inf), so even if the first loop iteration ran between two
  // of these calls it would cut. Ordering them after the outputs means no input can ever be
  // acted on before there is a defined output to act on it with.
  pwm_capture_init_channel(RC_KILL_SWITCH_GPIO);
  pwm_capture_init_channel(JETSON_STEERING_PWM_IN_GPIO);
  pwm_capture_init_channel(JETSON_THROTTLE_PWM_IN_GPIO);
  heartbeat_input_init(JETSON_HEARTBEAT_GPIO);

  // Seeded INVALID, never ARMED: a kill switch already parked inside its dead band at
  // power-on must resolve to KILL, and only a genuine move past the arm edge may arm it
  // (logic/src/rc_switch.c).
  RcSwitchPosition switch_position = RC_SWITCH_SIGNAL_INVALID;

  while (true) {
    MuxInput input;
    input.rc_kill_switch_pwm_us = pwm_capture_read_us(RC_KILL_SWITCH_GPIO);
    input.jetson_heartbeat_age_s = heartbeat_input_age_s();
    input.jetson_steering_pwm_us = pwm_capture_read_us(JETSON_STEERING_PWM_IN_GPIO);
    input.jetson_throttle_pwm_us = pwm_capture_read_us(JETSON_THROTTLE_PWM_IN_GPIO);
    input.previous_switch_position = switch_position;

    MuxOutput output = mux_decide(input, params);
    switch_position = output.switch_position;

    pwm_output_set_us(SERVO_PWM_OUT_GPIO, output.steering_out_us);
    pwm_output_set_us(ESC_PWM_OUT_GPIO, output.throttle_out_us);
    power_cutoff_set_enabled(POWER_CUTOFF_GPIO, !output.cut);

    sleep_ms(MUX_LOOP_PERIOD_MS);
  }
}
