// firmware/safety_mux Pico SDK glue: main loop tying the host-tested decision logic in
// firmware/safety_mux/logic/ to real RP2040 GPIO/PWM hardware. UNVERIFIED ON HARDWARE -- see
// firmware/safety_mux/README.md for what that means and what roadmap task 1.3's kill test
// still has to prove. This file is deliberately thin: every actual DECISION (mux state
// machine, watchdog timing, PWM validity) lives in logic/ and is called, never
// re-implemented, here.
//
// Pin assignments below match firmware/safety_mux/README.md's pinout table exactly --
// change one, change both, or the README stops being honest about what this code does.
#include <stdio.h>

#include "hardware/gpio.h"
#include "pico/stdlib.h"
#include "safety_mux/mux_decision.h"
#include "safety_mux/mux_params.h"
#include "vehicle_params_generated.h"  // generated by tools/gen_params.py at build time, see
                                        // CMakeLists.txt -- never hand-written, never committed
                                        // (claude-docs/06-vehicle-params.md rule 3)

#include "heartbeat_input.h"
#include "power_cutoff.h"
#include "pwm_capture.h"
#include "pwm_output.h"

#define RC_KILL_SWITCH_GPIO 2
#define JETSON_STEERING_PWM_IN_GPIO 3
#define JETSON_THROTTLE_PWM_IN_GPIO 4
#define JETSON_HEARTBEAT_GPIO 5
#define SERVO_PWM_OUT_GPIO 6
#define ESC_PWM_OUT_GPIO 7
#define POWER_CUTOFF_GPIO 8
#define FAULT_LED_GPIO PICO_DEFAULT_LED_PIN

#define MUX_LOOP_PERIOD_MS 5  // 200 Hz -- comfortably faster than a 50 Hz servo/ESC frame

// Builds a RawMuxParamFields from the generated vehicle_params C binding
// (vehicle_params_generated.h's static const VEHICLE_PARAMS instance, tools/gen_params.py's
// C emitter -- every nullable leaf there is a `<field>` + `<field>_is_set` pair). This is
// the ONE place safety_mux/mux_params.h's field names are wired to vehicle_params' actual
// schema paths; if config/vehicle_params.schema.json's field names ever change, this is
// where the build breaks (a compile error, not a silent mismatch).
static RawMuxParamFields raw_fields_from_generated_params(void) {
  RawMuxParamFields raw;
  raw.steering_pwm_min_us.value = VEHICLE_PARAMS.steering.pwm_min_us;
  raw.steering_pwm_min_us.is_set = VEHICLE_PARAMS.steering.pwm_min_us_is_set;
  raw.steering_pwm_max_us.value = VEHICLE_PARAMS.steering.pwm_max_us;
  raw.steering_pwm_max_us.is_set = VEHICLE_PARAMS.steering.pwm_max_us_is_set;
  raw.steering_pwm_neutral_us.value = VEHICLE_PARAMS.steering.pwm_neutral_us;
  raw.steering_pwm_neutral_us.is_set = VEHICLE_PARAMS.steering.pwm_neutral_us_is_set;
  raw.throttle_pwm_min_us.value = VEHICLE_PARAMS.actuation.throttle_pwm_min_us;
  raw.throttle_pwm_min_us.is_set = VEHICLE_PARAMS.actuation.throttle_pwm_min_us_is_set;
  raw.throttle_pwm_max_us.value = VEHICLE_PARAMS.actuation.throttle_pwm_max_us;
  raw.throttle_pwm_max_us.is_set = VEHICLE_PARAMS.actuation.throttle_pwm_max_us_is_set;
  raw.throttle_pwm_neutral_us.value = VEHICLE_PARAMS.actuation.throttle_pwm_neutral_us;
  raw.throttle_pwm_neutral_us.is_set = VEHICLE_PARAMS.actuation.throttle_pwm_neutral_us_is_set;
  raw.watchdog_timeout_s.value = VEHICLE_PARAMS.limits.mux_watchdog_timeout_s;
  raw.watchdog_timeout_s.is_set = VEHICLE_PARAMS.limits.mux_watchdog_timeout_s_is_set;
  raw.kill_switch_threshold_us.value = VEHICLE_PARAMS.limits.mux_kill_switch_threshold_us;
  raw.kill_switch_threshold_us.is_set =
      VEHICLE_PARAMS.limits.mux_kill_switch_threshold_us_is_set;
  // The RC receiver's own valid PWM signal range is NOT a vehicle_params field (it describes
  // the receiver/transmitter pair, not the vehicle) -- see README.md's pinout table. Bench
  // work must replace this with the receiver's datasheet-or-measured range before this
  // firmware leaves draft status; it is set here (not left to default-construct as unset)
  // specifically so that omission does not read as "just another missing vehicle_params
  // field" in the fault path below.
  raw.rc_signal_min_us.value = 1000.0;
  raw.rc_signal_min_us.is_set = true;
  raw.rc_signal_max_us.value = 2000.0;
  raw.rc_signal_max_us.is_set = true;
  return raw;
}

// Halts forever, blinking the fault LED and printing over USB serial, rather than running
// the control loop with an assumed default (CLAUDE.md invariant 2; this milestone's
// instruction: "the firmware build must fail loudly on nulls rather than assume defaults").
// Deliberately never returns.
static void fault_halt_missing_param(const char* missing_field) {
  gpio_init(FAULT_LED_GPIO);
  gpio_set_dir(FAULT_LED_GPIO, GPIO_OUT);
  while (true) {
    printf("FATAL: config/vehicle_params.yaml is missing a required safety_mux field: %s\n",
           missing_field);
    printf("This firmware refuses to arm without every field it needs. See "
           "firmware/safety_mux/README.md.\n");
    gpio_put(FAULT_LED_GPIO, true);
    sleep_ms(100);
    gpio_put(FAULT_LED_GPIO, false);
    sleep_ms(100);
  }
}

int main(void) {
  stdio_init_all();

  RawMuxParamFields raw = raw_fields_from_generated_params();
  MuxParamsResult params_result = mux_params_from_raw(raw);
  if (!params_result.ok) {
    fault_halt_missing_param(params_result.missing_field);
    // unreachable: fault_halt_missing_param() never returns.
  }
  MuxParams params = params_result.params;

  pwm_capture_init_channel(RC_KILL_SWITCH_GPIO);
  pwm_capture_init_channel(JETSON_STEERING_PWM_IN_GPIO);
  pwm_capture_init_channel(JETSON_THROTTLE_PWM_IN_GPIO);
  heartbeat_input_init(JETSON_HEARTBEAT_GPIO);
  pwm_output_init_channel(SERVO_PWM_OUT_GPIO);
  pwm_output_init_channel(ESC_PWM_OUT_GPIO);
  power_cutoff_init(POWER_CUTOFF_GPIO);

  while (true) {
    MuxInput input;
    input.rc_kill_switch_pwm_us = pwm_capture_read_us(RC_KILL_SWITCH_GPIO);
    input.jetson_heartbeat_age_s = heartbeat_input_age_s();
    input.jetson_steering_pwm_us = pwm_capture_read_us(JETSON_STEERING_PWM_IN_GPIO);
    input.jetson_throttle_pwm_us = pwm_capture_read_us(JETSON_THROTTLE_PWM_IN_GPIO);

    MuxOutput output = mux_decide(input, params);

    pwm_output_set_us(SERVO_PWM_OUT_GPIO, output.steering_out_us);
    pwm_output_set_us(ESC_PWM_OUT_GPIO, output.throttle_out_us);
    power_cutoff_set_enabled(POWER_CUTOFF_GPIO, !output.cut);

    sleep_ms(MUX_LOOP_PERIOD_MS);
  }
}
