"""L3 node tests for racer_gym_bridge's bridge_node (claude-docs/12-testing.md).

Launches the real node via launch_testing and drives it with a plain rclpy
client node, per the L3 checklist: nominal behavior, correct QoS (a
`reliable` subscriber must NOT see the `best_effort` /scan stream),
responds to /drive, clean shutdown.

Needs rclpy, the launch_testing family, and f1tenth_gym -- none of which
are available under the bare `uv run pytest` L1 run (see this package's
pyproject.toml). The `pytest.importorskip` calls below make that run skip
this whole module cleanly instead of erroring. This module DOES run for
real in CI: the ros-dev image now carries f1tenth_gym (same pinned SHA as
sim-cpu, docker/ros-dev/pyproject.toml) and colcon/launch_testing come
from the ROS apt repo baked into that image, so the `sim-bridge-test` CI
job (see .github/workflows/ci.yml) exercises this module through
`colcon test`.
"""

from __future__ import annotations

import math
import signal
import tempfile
import time
import unittest

import pytest

pytest.importorskip("rclpy")
pytest.importorskip("launch_testing")
pytest.importorskip("f1tenth_gym")
pytest.importorskip("tf2_msgs")

import launch
import launch_testing
import launch_testing.actions
import launch_testing.asserts
import rclpy
from ackermann_msgs.msg import AckermannDriveStamped
from launch_ros.actions import Node as LaunchNode
from nav_msgs.msg import OccupancyGrid, Odometry
from racer_gym_bridge.bridge_node import build_track_from_raceline
from rclpy.qos import DurabilityPolicy, HistoryPolicy, QoSProfile, ReliabilityPolicy
from sensor_msgs.msg import LaserScan
from std_srvs.srv import Trigger
from tf2_msgs.msg import TFMessage

# Fast, deterministic parameters for the test run: a higher step rate than
# the gym default (100 Hz) would give keeps the test itself quick without
# changing anything about correctness; a fixed seed keeps it deterministic.
_TEST_STEP_RATE_HZ = 20.0
_TEST_SEED = 7


_SQUARE_RACELINE_CSV = """\
# raceline for track_id=test_square (claude-docs/02-repo-layout.md)
# generated by hand for sim/bridge/racer_gym_bridge/test/test_bridge_node.py
# vehicle_params: schema_version=0.1.0, sysid_session_id=none-preliminary
# generation_params: track_shape=square
# columns: s_m,x_m,y_m,heading_rad,curvature_1pm,target_speed_mps
s_m,x_m,y_m,heading_rad,curvature_1pm,target_speed_mps
0.0,0.0,0.0,0.0,0.0,3.0
2.0,2.0,0.0,1.57,0.0,3.0
4.0,2.0,2.0,3.14,0.0,3.0
6.0,0.0,2.0,-1.57,0.0,3.0
"""


class TestBuildTrackFromRaceline(unittest.TestCase):
    """Not launch_testing-dependent: exercises the pure track-building function used by
    build_env's optional raceline_path parameter (roadmap task S.2)."""

    def test_builds_a_track_from_a_closed_loop_raceline(self):
        with tempfile.TemporaryDirectory() as tmp_dir:
            raceline_path = f"{tmp_dir}/raceline.csv"
            with open(raceline_path, "w") as f:
                f.write(_SQUARE_RACELINE_CSV)
            track = build_track_from_raceline(raceline_path)
        self.assertGreater(len(track.centerline.xs), 0)
        self.assertGreater(len(track.raceline.vxs), 0)


@pytest.mark.launch_test
def generate_test_description():
    bridge_node = LaunchNode(
        package="racer_gym_bridge",
        executable="bridge_node",
        name="bridge_node",
        parameters=[{"step_rate_hz": _TEST_STEP_RATE_HZ, "seed": _TEST_SEED}],
    )
    return launch.LaunchDescription(
        [
            bridge_node,
            launch_testing.actions.ReadyToTest(),
        ]
    )


def _reliable_qos() -> QoSProfile:
    return QoSProfile(
        reliability=ReliabilityPolicy.RELIABLE,
        history=HistoryPolicy.KEEP_LAST,
        depth=10,
    )


def _best_effort_qos() -> QoSProfile:
    return QoSProfile(
        reliability=ReliabilityPolicy.BEST_EFFORT,
        history=HistoryPolicy.KEEP_LAST,
        depth=10,
    )


def _transient_local_qos() -> QoSProfile:
    return QoSProfile(
        reliability=ReliabilityPolicy.RELIABLE,
        durability=DurabilityPolicy.TRANSIENT_LOCAL,
        history=HistoryPolicy.KEEP_LAST,
        depth=1,
    )


class TestBridgeNode(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        rclpy.init()
        cls._wait_for_bridge_up()

    @classmethod
    def tearDownClass(cls):
        rclpy.shutdown()

    @staticmethod
    def _wait_for_bridge_up() -> None:
        """Block until bridge_node has published at least one /scan message.

        f1tenth_gym numba-jits its scan/dynamics kernels on the first
        env.reset()/step() call, which BridgeNode.__init__ triggers before
        it ever starts its publish timer. On a cold CI runner that JIT
        warm-up can take much longer than any individual test's own timing
        budget -- without this barrier, whichever test happens to run
        first (alphabetically, unittest's default order) eats that cost
        and sees zero messages, while every later test passes because the
        JIT is already warm. Waiting here, once, for the whole class
        removes that order-dependent flakiness.
        """
        warmup_node = rclpy.create_node("test_bridge_node_warmup")
        try:
            received = []
            warmup_node.create_subscription(LaserScan, "/scan", received.append, _best_effort_qos())
            deadline = time.time() + 60.0
            while not received and time.time() < deadline:
                rclpy.spin_once(warmup_node, timeout_sec=0.2)
            if not received:
                raise RuntimeError("bridge_node did not publish /scan within 60s of launch")
        finally:
            warmup_node.destroy_node()

    def setUp(self):
        self.node = rclpy.create_node("test_bridge_node_client")

    def tearDown(self):
        self.node.destroy_node()

    def _spin_for(self, seconds: float) -> None:
        end = time.time() + seconds
        while time.time() < end:
            rclpy.spin_once(self.node, timeout_sec=0.05)

    def test_scan_publishes_best_effort_with_finite_ranges(self):
        received = []
        self.node.create_subscription(LaserScan, "/scan", received.append, _best_effort_qos())
        self._spin_for(3.0)

        self.assertGreater(len(received), 0, "no /scan messages received on a best_effort sub")
        msg = received[-1]
        self.assertGreater(len(msg.ranges), 0)
        self.assertTrue(
            all(math.isfinite(r) for r in msg.ranges),
            "non-finite value in /scan ranges",
        )
        self.assertGreater(msg.range_max, msg.range_min)
        self.assertAlmostEqual(
            msg.angle_increment,
            (msg.angle_max - msg.angle_min) / (len(msg.ranges) - 1),
            places=6,
        )

    def test_scan_rate_is_approximately_the_configured_step_rate(self):
        received = []
        self.node.create_subscription(LaserScan, "/scan", received.append, _best_effort_qos())
        window_s = 2.0
        self._spin_for(window_s)

        rate_hz = len(received) / window_s
        # Generous band: CI runners are not real-time, so only check we are
        # in the right ballpark rather than tightly bound.
        self.assertGreater(rate_hz, _TEST_STEP_RATE_HZ * 0.4)
        self.assertLess(rate_hz, _TEST_STEP_RATE_HZ * 2.5)

    def test_scan_is_best_effort_not_reliable(self):
        """A `reliable` subscriber must not see the `best_effort` /scan stream.

        This is the QoS check claude-docs/12-testing.md asks every node
        test to include, applied to prove /scan is genuinely best_effort
        (not accidentally left at a default reliable profile).
        """
        received = []
        self.node.create_subscription(LaserScan, "/scan", received.append, _reliable_qos())
        self._spin_for(2.0)
        self.assertEqual(
            len(received),
            0,
            "a reliable subscriber received /scan messages; QoS is not best_effort",
        )

    def test_drive_command_moves_the_car(self):
        odoms = []
        self.node.create_subscription(
            Odometry, "/sim/ground_truth_odom", odoms.append, _reliable_qos()
        )
        drive_pub = self.node.create_publisher(AckermannDriveStamped, "/drive", _reliable_qos())

        self._spin_for(0.5)  # let discovery settle before publishing

        cmd = AckermannDriveStamped()
        cmd.drive.steering_angle = 0.0
        cmd.drive.speed = 2.0

        end = time.time() + 3.0
        while time.time() < end:
            drive_pub.publish(cmd)
            rclpy.spin_once(self.node, timeout_sec=0.05)

        self.assertGreater(len(odoms), 0, "no /sim/ground_truth_odom messages received")
        self.assertGreater(
            odoms[-1].twist.twist.linear.x,
            0.1,
            "car did not respond to a forward /drive speed command",
        )

    def test_map_is_latched_and_a_late_joining_subscriber_receives_it(self):
        """Milestone 2: /sim/map is published once at startup on a transient_local publisher.
        A subscriber that joins well AFTER that (this test's setUp always runs after
        setUpClass's _wait_for_bridge_up barrier, i.e. long after bridge_node's one-shot
        publish) must still receive it from the publisher's latched history -- that is what
        "latched" means for a ROS 2 transient_local QoS pairing, not a live re-publish."""
        received = []
        self.node.create_subscription(
            OccupancyGrid, "/sim/map", received.append, _transient_local_qos()
        )
        # No further publishing happens for /sim/map after node startup -- a short spin is
        # enough to let discovery + the latched delivery happen; it is not waiting for a
        # live publish tick the way the /scan and /sim/ground_truth_odom tests above do.
        self._spin_for(3.0)

        self.assertEqual(
            len(received),
            1,
            "expected exactly one latched /sim/map message to a late-joining subscriber",
        )
        msg = received[0]
        self.assertEqual(msg.header.frame_id, "map")
        self.assertGreater(msg.info.width, 0)
        self.assertGreater(msg.info.height, 0)
        self.assertEqual(len(msg.data), msg.info.width * msg.info.height)
        # The default synthetic track (build_synthetic_track) is entirely open (no walls),
        # so every cell must decode to ROS "free" (0), never "occupied" (100) or garbage.
        self.assertTrue(all(v == 0 for v in msg.data))

    def test_map_is_not_delivered_to_a_volatile_subscriber(self):
        """QoS check (claude-docs/12-testing.md L3: "correct QoS ... a reliable subscriber
        actually rejects a best_effort mock", applied here to durability instead of
        reliability): a VOLATILE (the rclpy default) subscriber must NOT receive a message
        published before it existed -- proving /sim/map is genuinely transient_local, not
        accidentally left at a default volatile durability."""
        volatile_qos = QoSProfile(
            reliability=ReliabilityPolicy.RELIABLE,
            durability=DurabilityPolicy.VOLATILE,
            history=HistoryPolicy.KEEP_LAST,
            depth=1,
        )
        received = []
        self.node.create_subscription(OccupancyGrid, "/sim/map", received.append, volatile_qos)
        self._spin_for(3.0)
        self.assertEqual(
            len(received),
            0,
            "a volatile subscriber received the already-published /sim/map message; "
            "the publisher's durability is not transient_local",
        )

    def test_tf_map_to_base_link_is_broadcast_continuously(self):
        """Milestone 2: map -> base_link on /tf, published every step from sim ground
        truth (not once, unlike the static laser transform below)."""
        received = []
        self.node.create_subscription(TFMessage, "/tf", received.append, _reliable_qos())
        self._spin_for(2.0)

        map_to_base_link = [
            t
            for msg in received
            for t in msg.transforms
            if t.header.frame_id == "map" and t.child_frame_id == "base_link"
        ]
        self.assertGreater(
            len(map_to_base_link), 1, "map -> base_link was not broadcast continuously on /tf"
        )
        # "Continuously" also means the stamps actually advance, not one message repeated.
        stamps = {(t.header.stamp.sec, t.header.stamp.nanosec) for t in map_to_base_link}
        self.assertGreater(len(stamps), 1, "every map -> base_link transform had the same stamp")

    def test_static_laser_tf_matches_scan_frame_id(self):
        """Milestone 2: a static base_link -> laser transform exists on /tf_static, and its
        child_frame_id matches /scan's own header.frame_id -- the chain a 3D viewer needs to
        render /scan aligned with the vehicle."""
        scans = []
        self.node.create_subscription(LaserScan, "/scan", scans.append, _best_effort_qos())
        static_transforms = []
        self.node.create_subscription(
            TFMessage, "/tf_static", static_transforms.append, _transient_local_qos()
        )
        self._spin_for(3.0)

        self.assertGreater(len(scans), 0, "no /scan messages received")
        self.assertGreater(len(static_transforms), 0, "no /tf_static messages received")

        laser_transforms = [
            t
            for msg in static_transforms
            for t in msg.transforms
            if t.child_frame_id == scans[-1].header.frame_id
        ]
        self.assertEqual(
            len(laser_transforms),
            1,
            f"expected exactly one static transform whose child frame matches /scan's "
            f"frame_id ({scans[-1].header.frame_id!r})",
        )
        self.assertEqual(laser_transforms[0].header.frame_id, "base_link")

    def test_reset_service(self):
        client = self.node.create_client(Trigger, "/sim/reset")
        self.assertTrue(
            client.wait_for_service(timeout_sec=10.0), "/sim/reset service not available"
        )
        future = client.call_async(Trigger.Request())
        rclpy.spin_until_future_complete(self.node, future, timeout_sec=10.0)
        result = future.result()
        self.assertIsNotNone(result, "/sim/reset call did not complete")
        self.assertTrue(result.success)


@launch_testing.post_shutdown_test()
class TestBridgeNodeShutdown(unittest.TestCase):
    def test_clean_exit(self, proc_info):
        # launch_testing stops every launched process with SIGINT at the
        # end of the test session. rclpy's spin() can be deep inside a
        # non-interruptible C call (gym env.step()) when that signal
        # arrives, in which case the process is terminated by the signal
        # itself rather than returning control to our try/finally for a
        # sys.exit(0) -- Python/subprocess reports that as exit code
        # -SIGINT, not a crash. That is what "asked to stop, stopped" looks
        # like for this node, so it is an allowable clean-exit outcome
        # alongside 0, matching the common launch_testing pattern for
        # long-running ROS nodes.
        launch_testing.asserts.assertExitCodes(proc_info, allowable_exit_codes=[0, -signal.SIGINT])
