"""L1 tests for racer_gym_bridge.track_loader (claude-docs/12-testing.md), pure/ROS-free."""

from __future__ import annotations

import numpy as np
import pytest
from racer_gym_bridge.track_loader import (
    RacelineLoadError,
    build_corridor_occupancy,
    carve_pocket,
    load_raceline_xy_speed,
)

_FIXTURE_CSV = """\
# raceline for track_id=test_track (claude-docs/02-repo-layout.md)
# generated by hand for sim/bridge/racer_gym_bridge/test/test_track_loader.py
# vehicle_params: schema_version=0.1.0, sysid_session_id=none-preliminary
# generation_params: track_shape=square
# columns: s_m,x_m,y_m,heading_rad,curvature_1pm,target_speed_mps
s_m,x_m,y_m,heading_rad,curvature_1pm,target_speed_mps
0.0,0.0,0.0,0.0,0.0,3.0
1.0,1.0,0.0,0.0,0.0,4.0
2.0,1.0,1.0,1.57,0.0,5.0
"""


def test_loads_x_y_speed_arrays(tmp_path):
    path = tmp_path / "raceline.csv"
    path.write_text(_FIXTURE_CSV)

    x, y, speed = load_raceline_xy_speed(path)

    np.testing.assert_allclose(x, [0.0, 1.0, 1.0])
    np.testing.assert_allclose(y, [0.0, 0.0, 1.0])
    np.testing.assert_allclose(speed, [3.0, 4.0, 5.0])


def test_raises_on_missing_file(tmp_path):
    with pytest.raises(RacelineLoadError):
        load_raceline_xy_speed(tmp_path / "does_not_exist.csv")


def test_raises_on_bad_header(tmp_path):
    path = tmp_path / "raceline.csv"
    path.write_text("not,the,right,header\n1,2,3,4\n")
    with pytest.raises(RacelineLoadError):
        load_raceline_xy_speed(path)


def test_raises_on_empty_body(tmp_path):
    path = tmp_path / "raceline.csv"
    path.write_text("s_m,x_m,y_m,heading_rad,curvature_1pm,target_speed_mps\n")
    with pytest.raises(RacelineLoadError):
        load_raceline_xy_speed(path)


def test_raises_on_non_numeric_field(tmp_path):
    path = tmp_path / "raceline.csv"
    path.write_text(
        "s_m,x_m,y_m,heading_rad,curvature_1pm,target_speed_mps\n0.0,not_a_number,0.0,0.0,0.0,3.0\n"
    )
    with pytest.raises(RacelineLoadError):
        load_raceline_xy_speed(path)


# -- build_corridor_occupancy (GitHub issue 26: walls for the reactive-controller L5 canary) --

_SQUARE_X = np.array([0.0, 4.0, 4.0, 0.0])
_SQUARE_Y = np.array([0.0, 0.0, 4.0, 4.0])


def _cell_value(occupancy, origin, resolution, x, y):
    col = int((x - origin[0]) / resolution)
    row = int((y - origin[1]) / resolution)
    return occupancy[row, col]


def test_corridor_is_free_on_the_centerline_and_walled_outside_it():
    res = 0.05
    occ, origin = build_corridor_occupancy(_SQUARE_X, _SQUARE_Y, 0.5, res)
    # On the centerline, including the closing segment (0, 4) -> (0, 0).
    assert _cell_value(occ, origin, res, 2.0, 0.0) == 255.0
    assert _cell_value(occ, origin, res, 0.0, 2.0) == 255.0
    # Just inside and just outside the half width.
    assert _cell_value(occ, origin, res, 2.0, 0.45) == 255.0
    assert _cell_value(occ, origin, res, 2.0, 0.6) == 0.0
    # The infield and the outside are walls.
    assert _cell_value(occ, origin, res, 2.0, 2.0) == 0.0
    assert _cell_value(occ, origin, res, 2.0, -0.8) == 0.0


def test_corridor_layout_is_rows_y_columns_x():
    """f1tenth_gym's xy_2_rc reads map[row = y, col = x]. A wide, short loop must give a
    map with more columns than rows."""
    x = np.array([0.0, 10.0, 10.0, 0.0])
    y = np.array([0.0, 0.0, 2.0, 2.0])
    occ, origin = build_corridor_occupancy(x, y, 0.4, 0.1, border_m=0.5)
    rows, cols = occ.shape
    assert cols > rows
    assert origin == pytest.approx((-0.9, -0.9, 0.0))


def test_corridor_border_is_wall():
    occ, _ = build_corridor_occupancy(_SQUARE_X, _SQUARE_Y, 0.5, 0.05)
    assert np.all(occ[0, :] == 0.0)
    assert np.all(occ[-1, :] == 0.0)
    assert np.all(occ[:, 0] == 0.0)
    assert np.all(occ[:, -1] == 0.0)


@pytest.mark.parametrize("half_width, resolution", [(0.0, 0.05), (0.5, 0.0), (-1.0, 0.05)])
def test_corridor_rejects_non_positive_sizes(half_width, resolution):
    with pytest.raises(ValueError):
        build_corridor_occupancy(_SQUARE_X, _SQUARE_Y, half_width, resolution)


def test_corridor_rejects_bad_shapes():
    with pytest.raises(ValueError):
        build_corridor_occupancy(np.array([0.0]), np.array([0.0]), 0.5, 0.05)
    with pytest.raises(ValueError):
        build_corridor_occupancy(np.array([0.0, 1.0]), np.array([0.0]), 0.5, 0.05)


# -- carve_pocket (roadmap 2.9: a parking slot for park_node's L5 scenario) --------------------

_LONG_X = np.array([0.0, 10.0, 10.0, 0.0])
_LONG_Y = np.array([0.0, 0.0, 3.0, 3.0])


def _pocket_map(side: str):
    res = 0.05
    occ, origin = build_corridor_occupancy(_LONG_X, _LONG_Y, 0.5, res, border_m=1.5)
    carved = carve_pocket(occ, origin, res, _LONG_X, _LONG_Y, 0.5, 2.0, 1.5, 0.7, side)
    return occ, carved, origin, res


def test_pocket_pushes_the_right_wall_back_over_its_length():
    occ, carved, origin, res = _pocket_map("right")
    # The bottom straight runs +x at y = 0; right of travel is -y.
    assert _cell_value(occ, origin, res, 2.75, -0.9) == 0.0  # wall before carving
    assert _cell_value(carved, origin, res, 2.75, -0.9) == 255.0  # inside the pocket
    assert _cell_value(carved, origin, res, 2.75, -1.15) == 255.0  # near the back
    assert _cell_value(carved, origin, res, 2.75, -1.3) == 0.0  # beyond the back
    assert _cell_value(carved, origin, res, 1.9, -0.9) == 0.0  # before the pocket
    assert _cell_value(carved, origin, res, 3.6, -0.9) == 0.0  # after it
    assert _cell_value(carved, origin, res, 2.75, 0.9) == 0.0  # the left wall is untouched
    # Nothing else changed, and the input map is not modified.
    assert np.count_nonzero(carved != occ) > 0
    assert np.all(carved[occ == 255.0] == 255.0)


def test_pocket_on_the_left():
    _, carved, origin, res = _pocket_map("left")
    assert _cell_value(carved, origin, res, 2.75, 0.9) == 255.0
    assert _cell_value(carved, origin, res, 2.75, -0.9) == 0.0


def test_pocket_edges_are_within_half_a_cell():
    _, carved, origin, res = _pocket_map("right")
    free_x = [
        x
        for x in np.arange(1.5, 4.0, 0.01)
        if _cell_value(carved, origin, res, float(x), -0.9) == 255.0
    ]
    assert min(free_x) == pytest.approx(2.0, abs=res / 2 + 0.01)
    assert max(free_x) == pytest.approx(3.5, abs=res / 2 + 0.01)


@pytest.mark.parametrize(
    "start, length, depth, side",
    [
        (2.0, 0.0, 0.7, "right"),
        (2.0, 1.5, 0.0, "right"),
        (2.0, 1.5, 0.7, "up"),
        (25.0, 2.0, 0.7, "right"),
    ],
)
def test_pocket_rejects_bad_input(start, length, depth, side):
    occ, origin = build_corridor_occupancy(_LONG_X, _LONG_Y, 0.5, 0.05, border_m=1.5)
    with pytest.raises(ValueError):
        carve_pocket(occ, origin, 0.05, _LONG_X, _LONG_Y, 0.5, start, length, depth, side)
