"""L1 tests for racer_gym_bridge.track_loader (claude-docs/12-testing.md), pure/ROS-free."""

from __future__ import annotations

import numpy as np
import pytest
from racer_gym_bridge.track_loader import RacelineLoadError, load_raceline_xy_speed

_FIXTURE_CSV = """\
# raceline for track_id=test_track (claude-docs/02-repo-layout.md)
# generated by hand for sim/bridge/racer_gym_bridge/test/test_track_loader.py
# vehicle_params: schema_version=0.1.0, sysid_session_id=none-preliminary
# generation_params: track_shape=square
# columns: s_m,x_m,y_m,heading_rad,curvature_1pm,target_speed_mps
s_m,x_m,y_m,heading_rad,curvature_1pm,target_speed_mps
0.0,0.0,0.0,0.0,0.0,3.0
1.0,1.0,0.0,0.0,0.0,4.0
2.0,1.0,1.0,1.57,0.0,5.0
"""


def test_loads_x_y_speed_arrays(tmp_path):
    path = tmp_path / "raceline.csv"
    path.write_text(_FIXTURE_CSV)

    x, y, speed = load_raceline_xy_speed(path)

    np.testing.assert_allclose(x, [0.0, 1.0, 1.0])
    np.testing.assert_allclose(y, [0.0, 0.0, 1.0])
    np.testing.assert_allclose(speed, [3.0, 4.0, 5.0])


def test_raises_on_missing_file(tmp_path):
    with pytest.raises(RacelineLoadError):
        load_raceline_xy_speed(tmp_path / "does_not_exist.csv")


def test_raises_on_bad_header(tmp_path):
    path = tmp_path / "raceline.csv"
    path.write_text("not,the,right,header\n1,2,3,4\n")
    with pytest.raises(RacelineLoadError):
        load_raceline_xy_speed(path)


def test_raises_on_empty_body(tmp_path):
    path = tmp_path / "raceline.csv"
    path.write_text("s_m,x_m,y_m,heading_rad,curvature_1pm,target_speed_mps\n")
    with pytest.raises(RacelineLoadError):
        load_raceline_xy_speed(path)


def test_raises_on_non_numeric_field(tmp_path):
    path = tmp_path / "raceline.csv"
    path.write_text(
        "s_m,x_m,y_m,heading_rad,curvature_1pm,target_speed_mps\n0.0,not_a_number,0.0,0.0,0.0,3.0\n"
    )
    with pytest.raises(RacelineLoadError):
        load_raceline_xy_speed(path)
