"""What `verify_against_environment` compares a `Contract` against: a snapshot of what the
live deploy system actually reports, gathered by the (later, roadmap 5.2) `policy_node` from
its subscribed topics and from the generated `vehicle_params` binding.

`VehicleParamsMetaLike` is a structural `Protocol`, not an import of the generated bindings
module -- generated bindings are never committed (claude-docs/10-conventions.md,
claude-docs/06-vehicle-params.md rule 3) and are regenerated by `tools/gen_params.py`
wherever needed. This mirrors `training/envelope/src/envelope/params.py`'s
`VehicleParamsLike` pattern: typing against a Protocol means this package has no import-time
dependency on wherever the generated module happens to live, while mypy still checks real
callers structurally. The real `VehicleParams.meta` (see config/vehicle_params.schema.json
`meta`) satisfies this Protocol directly.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Protocol

from racer_policy.contract import ObservationField


class VehicleParamsMetaLike(Protocol):
    schema_version: str
    sysid_session_id: str


class VehicleParamsLike(Protocol):
    meta: VehicleParamsMetaLike


@dataclass(frozen=True)
class LiveObservationSchema:
    """The observation fields and LiDAR configuration the deploy system is actually
    publishing right now, in the order the policy_node will assemble them into an
    observation vector."""

    fields: tuple[ObservationField, ...]
    lidar_beam_count: int
    lidar_fov_rad: float
    lidar_downsample_factor: int


@dataclass(frozen=True)
class LiveEnvironment:
    """Everything `verify_against_environment` needs to know about the running system.

    `vehicle_params` is expected to be (or structurally match) the generated
    `VehicleParams` instance's `.meta`-bearing root object -- i.e. pass the real
    `VEHICLE_PARAMS` from the generated binding, not a hand-copied stand-in
    (claude-docs/06-vehicle-params.md rule 1: no hand-written physical/version constants).
    """

    vehicle_params: VehicleParamsLike
    observation: LiveObservationSchema
