"""Provenanced raceline CSV read/write (claude-docs/02-repo-layout.md: `config/tracks/`).

A committed raceline file is a `#`-commented provenance header (tool version, the
`vehicle_params` schema_version/sysid_session_id it was generated against, and the
generation parameters used) followed by a plain CSV body with a header row and columns
``s_m,x_m,y_m,heading_rad,curvature_1pm,target_speed_mps`` (claude-docs/00-project-overview.md
/ CLAUDE.md task brief's committed column set). `#`-prefixed lines are ignored by any
generic CSV reader that skips comments, but ``read_raceline_csv`` also parses them back out
so tests and tooling can check what produced a committed file without re-deriving it.
"""

from __future__ import annotations

import csv
from dataclasses import dataclass
from pathlib import Path

import numpy as np

from raceline.raceline import Raceline

TOOL_VERSION = "0.1.0"

_COLUMNS = ("s_m", "x_m", "y_m", "heading_rad", "curvature_1pm", "target_speed_mps")


@dataclass(frozen=True)
class Provenance:
    tool_version: str
    vehicle_params_schema_version: str
    vehicle_params_sysid_session_id: str
    generation_params: dict[str, str]


def write_raceline_csv(
    path: Path,
    raceline: Raceline,
    *,
    track_id: str,
    vehicle_params_schema_version: str,
    vehicle_params_sysid_session_id: str,
    generation_params: dict[str, float | str],
) -> None:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)

    gen_params_str = ", ".join(f"{k}={v}" for k, v in generation_params.items())
    header_lines = [
        f"# raceline for track_id={track_id} (claude-docs/02-repo-layout.md)",
        f"# generated by tools/raceline (tool_version={TOOL_VERSION})",
        (
            f"# vehicle_params: schema_version={vehicle_params_schema_version}, "
            f"sysid_session_id={vehicle_params_sysid_session_id}"
        ),
        f"# generation_params: {gen_params_str}",
        "# columns: " + ",".join(_COLUMNS),
    ]

    with path.open("w", newline="", encoding="utf-8") as f:
        for line in header_lines:
            f.write(line + "\n")
        # lineterminator="\n": csv.writer's default is "\r\n" (RFC 4180), which would leave
        # a trailing "\r" on every field the simple C++ reader
        # (ros_ws/src/racer_control/include/racer_control/raceline.hpp) parses with
        # std::getline (splits on "\n" only) -- silently corrupting the last column of
        # every row (a "\r"-contaminated target_speed_mps) and, on the header row, failing
        # its exact string match. Plain "\n" keeps this file consistent with the
        # "#"-commented header lines above, which are written with "\n" directly.
        writer = csv.writer(f, lineterminator="\n")
        writer.writerow(_COLUMNS)
        for i in range(len(raceline)):
            writer.writerow(
                [
                    f"{raceline.s_m[i]:.6f}",
                    f"{raceline.x_m[i]:.6f}",
                    f"{raceline.y_m[i]:.6f}",
                    f"{raceline.heading_rad[i]:.6f}",
                    f"{raceline.curvature_1pm[i]:.6f}",
                    f"{raceline.target_speed_mps[i]:.6f}",
                ]
            )


def _parse_provenance(header_lines: list[str]) -> Provenance:
    tool_version = ""
    schema_version = ""
    sysid_session_id = ""
    generation_params: dict[str, str] = {}
    for line in header_lines:
        text = line.lstrip("#").strip()
        if text.startswith("generated by tools/raceline"):
            # "generated by tools/raceline (tool_version=0.1.0)"
            start = text.find("tool_version=")
            if start != -1:
                tool_version = text[start + len("tool_version=") :].rstrip(")").strip()
        elif text.startswith("vehicle_params:"):
            rest = text[len("vehicle_params:") :]
            for part in rest.split(","):
                if "=" in part:
                    k, v = part.split("=", 1)
                    k, v = k.strip(), v.strip()
                    if k == "schema_version":
                        schema_version = v
                    elif k == "sysid_session_id":
                        sysid_session_id = v
        elif text.startswith("generation_params:"):
            rest = text[len("generation_params:") :]
            for part in rest.split(","):
                if "=" in part:
                    k, v = part.split("=", 1)
                    generation_params[k.strip()] = v.strip()
    return Provenance(
        tool_version=tool_version,
        vehicle_params_schema_version=schema_version,
        vehicle_params_sysid_session_id=sysid_session_id,
        generation_params=generation_params,
    )


def read_external_centerline_csv(path: Path) -> tuple[np.ndarray, np.ndarray]:
    """Read an externally-sourced closed-loop centerline CSV and return its ``(x_m, y_m)``
    arrays -- the raw input `raceline.build_raceline_from_centerline` (the EXISTING S.2
    optimizer pipeline, unmodified) needs, same as `synthetic_tracks.stadium_centerline`
    already provides for the synthetic case.

    Format (matches f1tenth_racetracks' own centerline export, e.g. `config/tracks/
    oschersleben/source_centerline.csv`): an optional leading ``#``-commented provenance
    block (skipped), then a header line whose first field is non-numeric (also skipped, so
    this tolerates a plain ``x_m, y_m, ...`` header OR no header at all), then one row per
    point with ``x_m`` and ``y_m`` as the FIRST TWO comma-separated fields -- any further
    columns (e.g. f1tenth_racetracks' track-width columns) are ignored, since this repo's
    bridge has no real occupancy-map/wall model to use them with yet (see
    `config/tracks/oschersleben/source_centerline.csv`'s own header comment).
    """
    path = Path(path)
    if not path.is_file():
        raise ValueError(f"centerline file not found: {path}")

    xs: list[float] = []
    ys: list[float] = []
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            if line.startswith("#") or not line.strip():
                continue
            fields = next(csv.reader([line]))
            if len(fields) < 2:
                continue
            try:
                x = float(fields[0])
                y = float(fields[1])
            except ValueError:
                continue  # a non-numeric header row -- skip, not an error (see docstring)
            xs.append(x)
            ys.append(y)

    if not xs:
        raise ValueError(f"{path}: no numeric (x_m, y_m) rows found")
    return np.array(xs), np.array(ys)


def read_raceline_csv(path: Path) -> tuple[Raceline, Provenance]:
    path = Path(path)
    header_lines: list[str] = []
    rows: list[list[str]] = []
    with path.open("r", encoding="utf-8") as f:
        for raw_line in f:
            if raw_line.startswith("#"):
                header_lines.append(raw_line.rstrip("\n"))
            else:
                rows.append(raw_line.rstrip("\n"))

    reader = csv.reader(rows)
    body = list(reader)
    if not body:
        raise ValueError(f"{path}: no CSV body found")
    header_row = tuple(body[0])
    if header_row != _COLUMNS:
        raise ValueError(f"{path}: expected columns {_COLUMNS}, got {header_row}")
    data_rows = body[1:]
    if not data_rows:
        raise ValueError(f"{path}: no data rows found")

    arr = np.array(data_rows, dtype=float)
    raceline = Raceline(
        s_m=arr[:, 0],
        x_m=arr[:, 1],
        y_m=arr[:, 2],
        heading_rad=arr[:, 3],
        curvature_1pm=arr[:, 4],
        target_speed_mps=arr[:, 5],
    )
    return raceline, _parse_provenance(header_lines)
