"""Loads `vehicle_params` via the GENERATED Python binding, never by hand-parsing the yaml.

claude-docs/06-vehicle-params.md rule 3: bindings are generated by `tools/gen_params.py`
and never hand-written; claude-docs/10-conventions.md / CLAUDE.md invariant 2: never
hand-write a physical constant. This module calls the same `gen_params.generate_python`
function CI uses to build `vehicle_params_generated.py`, but writes the result to a
throwaway temp file and imports it in-memory -- it is never written into the source tree
(the repo's `.gitignore` already refuses `*_generated.py`; this module simply never
attempts to write one there in the first place).
"""

from __future__ import annotations

import importlib.util
import sys
import tempfile
from pathlib import Path
from typing import Any

# tools/ (this package's parent) holds gen_params.py as a top-level module, imported the
# same way tools/conftest.py makes it importable to tools/tests/*.py: by being on sys.path.
_TOOLS_DIR = Path(__file__).resolve().parents[1]
if str(_TOOLS_DIR) not in sys.path:
    sys.path.insert(0, str(_TOOLS_DIR))

import gen_params


def load_vehicle_params(params_path: Path | None = None, schema_path: Path | None = None) -> Any:
    """Validate `vehicle_params.yaml` against its schema and return the generated
    `VEHICLE_PARAMS` binding instance (a frozen dataclass tree), imported in-memory.
    """
    repo_root = _TOOLS_DIR.parent
    params_path = params_path or (repo_root / gen_params.DEFAULT_PARAMS_PATH)
    schema_path = schema_path or (repo_root / gen_params.DEFAULT_SCHEMA_PATH)

    params = gen_params.load_yaml_file(params_path)
    schema = gen_params.load_schema_file(schema_path)
    gen_params.validate_params(params, schema)
    py_source = gen_params.generate_python(params, schema)

    with tempfile.TemporaryDirectory() as tmp_dir:
        module_path = Path(tmp_dir) / "vehicle_params_generated.py"
        module_path.write_text(py_source, encoding="utf-8")
        spec = importlib.util.spec_from_file_location("vehicle_params_generated", module_path)
        assert spec is not None and spec.loader is not None
        module = importlib.util.module_from_spec(spec)
        # dataclasses (used by the generated module) resolves string field annotations via
        # sys.modules[cls.__module__], so the module must be registered before exec_module
        # runs (same fix as tools/tests/test_gen_params.py's own generated-module import).
        sys.modules[spec.name] = module
        try:
            spec.loader.exec_module(module)
        finally:
            del sys.modules[spec.name]

    return module.VEHICLE_PARAMS
