"""Loads config/vehicle_params.yaml through the GENERATED Python binding
(tools/gen_params.py) for keyboard_teleop_node's step-size/cap derivation (CLAUDE.md
invariant 2: never hand-write a physical constant; claude-docs/06-vehicle-params.md rule 3:
bindings are generated, never committed).

racer_tools is an ament_python (colcon) package, always run from within this one ROS
workspace -- unlike sim/racer_gym, which can be installed as a plain `uv` path dependency of
OTHER packages elsewhere on disk (see sim/racer_gym/racer_gym/params.py's
`discover_repo_root` for that harder, multi-anchor problem). Every build script in this repo
uses `colcon build --symlink-install`, which keeps `__file__` pointing at this real source
file rather than a copy, so a fixed relative walk-up is safe here -- the same pattern
racer_control's/racer_safety's CMakeLists.txt already use to locate the repo root for the C++
binding. `python3-yaml`/`python3-jsonschema` (racer_tools/package.xml `<depend>`s, resolved
by rosdep) put tools/gen_params.py's own dependencies on the system python3 that ament_python
nodes run under, so this loads it in-process via importlib -- no subprocess, and no
dependency on `uv` being on PATH at node runtime (unlike the C++ side's build-time
generation, which does shell out to `uv run`).
"""

from __future__ import annotations

import importlib.util
import sys
import types
from pathlib import Path
from typing import Any

_THIS_FILE = Path(__file__).resolve()
# vehicle_params_loader.py -> racer_tools/ (python pkg) -> racer_tools/ (ROS pkg dir) -> src
# -> ros_ws -> repo root.
_REPO_ROOT = _THIS_FILE.parents[4]
_GEN_PARAMS_PATH = _REPO_ROOT / "tools" / "gen_params.py"
_PARAMS_PATH = _REPO_ROOT / "config" / "vehicle_params.yaml"
_SCHEMA_PATH = _REPO_ROOT / "config" / "vehicle_params.schema.json"


def _require(path: Path, what: str) -> Path:
    if not path.is_file():
        raise RuntimeError(
            f"racer_tools.vehicle_params_loader: expected {what} at {path!s} (computed from "
            f"{_THIS_FILE!s} assuming a colcon --symlink-install layout: "
            "ros_ws/src/racer_tools/racer_tools/vehicle_params_loader.py). "
            "keyboard_teleop_node must be run from within a fast-car checkout's ros_ws "
            "colcon workspace."
        )
    return path


def _load_gen_params_module() -> types.ModuleType:
    gen_params_path = _require(_GEN_PARAMS_PATH, "tools/gen_params.py")
    spec = importlib.util.spec_from_file_location("racer_tools._gen_params", gen_params_path)
    if spec is None or spec.loader is None:  # pragma: no cover - defensive
        raise ImportError(f"could not load gen_params.py from {gen_params_path}")
    module = importlib.util.module_from_spec(spec)
    # dataclasses.dataclass() (used by gen_params.FieldShape/RecordType) looks the defining
    # module up in sys.modules by name; it must be registered before exec_module runs.
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def load_vehicle_params() -> Any:
    """Return the generated VehicleParams dataclass instance (VEHICLE_PARAMS), regenerated
    fresh from the committed config/vehicle_params.yaml every call (never committed itself,
    claude-docs/10-conventions.md)."""
    gen_params = _load_gen_params_module()
    params_path = _require(_PARAMS_PATH, "config/vehicle_params.yaml")
    schema_path = _require(_SCHEMA_PATH, "config/vehicle_params.schema.json")
    params = gen_params.load_yaml_file(params_path)
    schema = gen_params.load_schema_file(schema_path)
    gen_params.validate_params(params, schema)  # refuses (raises) on any mismatch, rule 06-2
    source = gen_params.generate_python(params, schema)

    module_name = "racer_tools._vehicle_params_generated"
    module = types.ModuleType(module_name)
    module.__file__ = "<generated by tools/gen_params.py, not committed>"
    sys.modules[module_name] = module
    exec(compile(source, module.__file__, "exec"), module.__dict__)  # noqa: S102
    return module.VEHICLE_PARAMS
