"""EnvelopeConfig: the fixed, validated numbers `apply` clips against.

Per claude-docs/06-vehicle-params.md, physical constants live ONLY in
`config/vehicle_params.yaml` and reach code through generated bindings -- never hand-written.
`EnvelopeConfig.from_vehicle_params` is the wiring point: it reads the base-command ranges
and the (currently unset) envelope fractions off a generated `VehicleParams`-shaped object.

`VehicleParamsLike` below is a structural (`Protocol`) view of just the fields this library
needs, not an import of the generated module -- the generated bindings are never committed
(claude-docs/10-conventions.md) and are regenerated by `tools/gen_params.py` wherever they're
needed (in CI, and at test time here). Typing against a Protocol means `envelope` has no
import-time dependency on wherever that generated file happens to live, while mypy still
checks real callers structurally.

Two of the four things layer 4 needs a number for currently have NO dedicated
`vehicle_params.limits` field at all:

  * `residual_fraction_steering` -- the schema has `envelope_fraction_lateral_accel`, which
    is about lateral-acceleration authority, not steering-angle-range fraction. Reusing it
    here would misrepresent what that field means, so it is not wired at all; this argument
    is always required explicitly until a real field for it exists (flagged for whoever
    tackles Phase 5 tuning).
  * rate limits and the speed cap -- claude-docs/05-safety.md lists these as layer-4
    concerns but the schema does not yet carry them (the speed cap is explicitly "cap value
    injected; the fidelity-curve-derived value arrives in Phase 3" per the S.4 task
    description). Both are always explicit constructor arguments.

`residual_fraction_speed` DOES have a dedicated field, `limits.envelope_fraction_speed`; it
is currently `null` (Phase 5 has not tuned it), so `from_vehicle_params` accepts an explicit
override and only falls back to reading the params field when no override is given. Once
Phase 5 lands a real value, callers can simply stop passing the override.
"""

from __future__ import annotations

import math
from dataclasses import dataclass
from typing import Protocol

from envelope.ood import OODScorer


class SteeringParamsLike(Protocol):
    min_angle_rad: float | None
    max_angle_rad: float | None


class LimitsParamsLike(Protocol):
    global_speed_cap_mps: float
    min_velocity_mps: float
    envelope_fraction_speed: float | None


class VehicleParamsLike(Protocol):
    steering: SteeringParamsLike
    limits: LimitsParamsLike


def _require_finite(name: str, value: float) -> None:
    if not math.isfinite(value):
        raise ValueError(f"{name} must be finite, got {value!r}")


def _require_finite_range(name: str, low: float, high: float) -> None:
    _require_finite(f"{name} (low)", low)
    _require_finite(f"{name} (high)", high)
    if low > high:
        raise ValueError(f"{name} must have low <= high, got ({low!r}, {high!r})")


def _require_fraction(name: str, value: float) -> None:
    _require_finite(name, value)
    if not (0.0 <= value <= 1.0):
        raise ValueError(f"{name} must be within [0, 1], got {value!r}")


def _require_nonneg(name: str, value: float) -> None:
    _require_finite(name, value)
    if value < 0.0:
        raise ValueError(f"{name} must be >= 0, got {value!r}")


@dataclass(frozen=True)
class EnvelopeConfig:
    """Everything `apply` needs that does not change from one call to the next.

    `steering_range` / `speed_range` are the LEGAL command ranges (the base controller's
    command range), `(low, high)`, `low <= high`. `residual_fraction_*` bound how much of
    that range's WIDTH the residual may add or subtract, as a fraction in `[0, 1]`.
    `max_delta_*` are rate limits: the maximum change in the OUTPUT command allowed in one
    `apply` call, in the same units as the corresponding range (this library is call-rate
    agnostic on purpose -- see `envelope.envelope` module docstring). `speed_cap_mps` further
    caps the top of `speed_range` (it can only tighten, never loosen, the speed ceiling).
    """

    steering_range: tuple[float, float]
    speed_range: tuple[float, float]
    residual_fraction_steering: float
    residual_fraction_speed: float
    max_delta_steering_rad: float
    max_delta_speed_mps: float
    speed_cap_mps: float
    ood_threshold: float
    ood_scorer: OODScorer

    def __post_init__(self) -> None:
        _require_finite_range("steering_range", *self.steering_range)
        _require_finite_range("speed_range", *self.speed_range)
        _require_fraction("residual_fraction_steering", self.residual_fraction_steering)
        _require_fraction("residual_fraction_speed", self.residual_fraction_speed)
        _require_nonneg("max_delta_steering_rad", self.max_delta_steering_rad)
        _require_nonneg("max_delta_speed_mps", self.max_delta_speed_mps)
        # speed_cap_mps is not required to be >= 0 in isolation (a config could sensibly cap
        # a reverse-only command range below zero); what matters is that it does not make the
        # effective speed ceiling fall below the effective speed floor, checked next.
        _require_finite("speed_cap_mps", self.speed_cap_mps)
        _require_nonneg("ood_threshold", self.ood_threshold)
        if self.speed_cap_mps < self.speed_range[0]:
            raise ValueError(
                "speed_cap_mps must be >= speed_range[0] (the reverse/min-velocity bound), "
                f"got speed_cap_mps={self.speed_cap_mps!r}, speed_range={self.speed_range!r}"
            )
        if not hasattr(self.ood_scorer, "score"):
            raise TypeError("ood_scorer must implement OODScorer (a .score(state) method)")

    @classmethod
    def from_vehicle_params(
        cls,
        params: VehicleParamsLike,
        ood_scorer: OODScorer,
        *,
        residual_fraction_steering: float,
        max_delta_steering_rad: float,
        max_delta_speed_mps: float,
        speed_cap_mps: float,
        ood_threshold: float,
        residual_fraction_speed: float | None = None,
    ) -> EnvelopeConfig:
        """Build a config from a generated `VehicleParams`-shaped object.

        `residual_fraction_speed`, if given, overrides `params.limits.envelope_fraction_speed`;
        if not given, that params field is used, and it is an error for both to be unset (see
        module docstring). `residual_fraction_steering` has no params field to fall back to at
        all yet, so it is always required here.
        """
        steering = params.steering
        limits = params.limits

        if steering.min_angle_rad is None or steering.max_angle_rad is None:
            raise ValueError(
                "vehicle_params.steering angle range is null; a chassis measurement "
                "(claude-docs/06-vehicle-params.md) must land before an envelope can be "
                "built from params -- construct EnvelopeConfig directly in the meantime."
            )
        steering_range = (steering.min_angle_rad, steering.max_angle_rad)
        speed_range = (limits.min_velocity_mps, limits.global_speed_cap_mps)

        resolved_speed_fraction: float | None
        if residual_fraction_speed is not None:
            resolved_speed_fraction = residual_fraction_speed
        else:
            resolved_speed_fraction = limits.envelope_fraction_speed
        if resolved_speed_fraction is None:
            raise ValueError(
                "residual_fraction_speed was not given and "
                "vehicle_params.limits.envelope_fraction_speed is null (Phase 5 tuning has "
                "not landed it yet, claude-docs/08-learning.md); pass it explicitly."
            )

        return cls(
            steering_range=steering_range,
            speed_range=speed_range,
            residual_fraction_steering=residual_fraction_steering,
            residual_fraction_speed=resolved_speed_fraction,
            max_delta_steering_rad=max_delta_steering_rad,
            max_delta_speed_mps=max_delta_speed_mps,
            speed_cap_mps=speed_cap_mps,
            ood_threshold=ood_threshold,
            ood_scorer=ood_scorer,
        )
